# Basic
title: Lei Ma
subtitle: Lei's homepage.
#welcome_message: My simple personal website.
description: Under construction...


url: "http://malei.me"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: 

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
 - {title: CV Page, description: My CV Page, url: 'http://maleiready.github.io/cv.html'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll]
paginate: 18
paginate_path: "page/:num/"

# Comment
comment: 
    disqus: https-maleiready-github-io
    # duoshuo: 
    
# Social
social:
#    weibo: onevcat
    github: maleiwhat
#    twitter: onevcat
#    gplus: 107108267983477358170
    mail: malei@outlook.com

# Google Analytics
ga:
     id: UA-126172926-1
     host: maleiready.github.io

     markdown: redcarpet